config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resource :base, only: [:show]
  root to: 'base#show'

  devise_for :users

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resource :profile, only: [:show, :update]

      resource :upload, only: [:create]
    end
  end

  get "/web/*id" => 'web#show', as: :web, format: false

  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :users

  validates :name_ru, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :city

  mount_uploader :pic, UsersUploader
  process_in_background :pic
  store_in_background :pic

  def full_name
    "#{first_name} #{second_name}"
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ApplicationController
  respond_to :json

end

app/controllers/api/v1/profiles_controller.rb
class Api::V1::ProfilesController < Api::V1::ApplicationController
  before_filter :authenticate_user!
  before_filter :get_user

  def show
    respond_with(@user, location: nil)
  end

  def update
    @user.update_attributes(params[:user])
    respond_with(@user, location: nil)
  end

  private

  def get_user
    @user = current_user
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  before_filter :authenticate_user!, only: [:update]

  def index
    search = User.search(params[:q])
    @users = filter.page(params[:page]).per(20)
    respond_with(@users, location: nil)
  end

  def show
    @user = User.find(params[:id])
    respond_with(@user, location: nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  before_filter :authenticate_user!

  def show
  end

end

app/controllers/web_controller.rb
class WebController < ApplicationController

  before_filter :authenticate_user!

  def show
    render "web/#{params[:id]}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/base/show.html.haml
.h1 Wellcome!

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Template
    = javascript_include_tag "application"
    = stylesheet_link_tag "application"
    = csrf_meta_tags
  %body
    .container
      = render 'shared/header'
      = yield

app/views/shared/_header.html.haml
%header
.navbar
  .navbar-inner
    %ul.nav
      %li.active
        = link_to t('.users_link'), web_path(:users)

      - if signed_in?
        %li= current_user.full_name
      %li= link_to t('.sign_out_link'), destroy_user_session_path, method: 'delete'

app/views/web/about.html.haml
ABOUT

app/views/web/users.html.haml
.h1 Users